using System;
using System.Collections.Generic;
using System.Text;

namespace SkyApm.Diagnostics.FreeRedis
{
    internal static class FreeRedisPluginConfig
    {
        internal static HashSet<String> OPERATION_MAPPING_WRITE = new HashSet<string>() {
                    "GETSET",
                    "SET",
                    "SETBIT",
                    "SETEX ",
                    "SETNX ",
                    "SETRANGE",
                    "STRLEN ",
                    "MSET",
                    "MSETNX ",
                    "PSETEX",
                    "INCR ",
                    "INCRBY ",
                    "INCRBYFLOAT",
                    "DECR ",
                    "DECRBY ",
                    "APPEND ",
                    "HMSET",
                    "HSET",
                    "HSETNX ",
                    "HINCRBY",
                    "HINCRBYFLOAT",
                    "HDEL",
                    "RPOPLPUSH",
                    "RPUSH",
                    "RPUSHX",
                    "LPUSH",
                    "LPUSHX",
                    "LREM",
                    "LTRIM",
                    "LSET",
                    "BRPOPLPUSH",
                    "LINSERT",
                    "SADD",
                    "SDIFF",
                    "SDIFFSTORE",
                    "SINTERSTORE",
                    "SISMEMBER",
                    "SREM",
                    "SUNION",
                    "SUNIONSTORE",
                    "SINTER",
                    "ZADD",
                    "ZINCRBY",
                    "ZINTERSTORE",
                    "ZRANGE",
                    "ZRANGEBYLEX",
                    "ZRANGEBYSCORE",
                    "ZRANK",
                    "ZREM",
                    "ZREMRANGEBYLEX",
                    "ZREMRANGEBYRANK",
                    "ZREMRANGEBYSCORE",
                    "ZREVRANGE",
                    "ZREVRANGEBYSCORE",
                    "ZREVRANK",
                    "ZUNIONSTORE",
                    "XADD",
                    "XDEL",
                    "DEL",
                    "XTRIM"
                };
        internal static HashSet<String> OPERATION_MAPPING_READ = new HashSet<string>(){
                    "GET",
                    "GETRANGE",
                    "GETBIT ",
                    "MGET",
                    "HVALS",
                    "HKEYS",
                    "HLEN",
                    "HEXISTS",
                    "HGET",
                    "HGETALL",
                    "HMGET",
                    "BLPOP",
                    "BRPOP",
                    "LINDEX",
                    "LLEN",
                    "LPOP",
                    "LRANGE",
                    "RPOP",
                    "SCARD",
                    "SRANDMEMBER",
                    "SPOP",
                    "SSCAN",
                    "SMOVE",
                    "ZLEXCOUNT",
                    "ZSCORE",
                    "ZSCAN",
                    "ZCARD",
                    "ZCOUNT",
                    "XGET",
                    "GET",
                    "XREAD",
                    "XLEN",
                    "XRANGE",
                    "XREVRANGE"
            };
    }
}
