name: NET CI AND IT

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  net7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Setup Submodule
      run: git submodule update --init
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Protocol
      run: dotnet build src/SkyApm.Transport.Protocol --no-restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --framework net8.0
